spring:
  application:
    name: ryan-information
  datasource:
    url: jdbc:h2:mem:information
    driverClassName: org.h2.Driver
    username: ryan
    password: 1
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  devtools:
    livereload:
      enabled: true

server:
  port: 8080


security:
  oauth2:
    resource:
      jwt:
        key-value:
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnP/0MjoDyGYEUkYvNF1l
          qo/1gcLCF5G6R5HevzovTR3ztt9aTJtH09vB9xtk/8tzoyt66zhz8rfdrT5c1lWk
          aQJRBmDMycxMQP0G1900bRGY+WwcR/DZ27do5q3alICVXL7lExBCmvFWIuIFUpAb
          ZPvuYCsrVk61KHi0fCnhm1n8Fo1lg4Kax+7Fl3Kj73Gahfvm228LyyowV2QGuoPB
          lPJpxJMoXYtBbZcPkfv0GfJCjEOGtmm7/4UTLAanRR6igl1TWCpst9hgOf+RMvCX
          zO6uO17F6MDmQvWZY8p9cQpwHqiWaDzwQjA9nI6fpOMPn5iAijpKFhMhWOYgkCnI
          lQIDAQAB
          -----END PUBLIC KEY-----